<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Facebook</name>
   <tag></tag>
   <elementGuidId>8646b8e0-c929-46c6-8164-34ae9c84df0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.JindexFooterFB.JsocialFB.JindexNaviRightBtmSocialFB.nav-link.JindexFooterFBJsocialFBJindexNaviRightBtmSocialFB.nav-link-https--wwwfacebookcom-petronas-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bdb5d89-60a7-4e17-928d-b212ff28e04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.facebook.com/petronas/</value>
      <webElementGuid>90807a7c-1e3e-4341-a0a6-28d39703b93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>24e24a3e-a734-4828-a198-1158e02869d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JindexFooterFB JsocialFB JindexNaviRightBtmSocialFB nav-link JindexFooterFBJsocialFBJindexNaviRightBtmSocialFB nav-link-https--wwwfacebookcom-petronas-</value>
      <webElementGuid>8ba831f3-001e-465e-b326-fbe139e5b991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>45b0420a-d4eb-4891-b1f6-4211be6f13da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexHomeDesktop&quot;]/div[@class=&quot;JindexFooter&quot;]/div[@class=&quot;JindexFooterInner&quot;]/div[@class=&quot;JindexFooterInnerBtm&quot;]/div[@class=&quot;JindexFooterInnerBtmRight&quot;]/ul[@class=&quot;clearfix nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;JindexFooterFB JsocialFB JindexNaviRightBtmSocialFB nav-link JindexFooterFBJsocialFBJindexNaviRightBtmSocialFB nav-link-https--wwwfacebookcom-petronas-&quot;]</value>
      <webElementGuid>c8f73b91-a0a9-4166-a587-837944ed83c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li/a</value>
      <webElementGuid>4b22c77f-dd2c-49a1-9cd3-c971cf3a79c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Facebook')])[3]</value>
      <webElementGuid>354ae24c-7ccb-4a0c-b0a6-a3713008f738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(20076-K)'])[1]/following::a[1]</value>
      <webElementGuid>02018951-aa2c-46d9-8c3f-b12c0bfa26fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect With Us'])[1]/following::a[1]</value>
      <webElementGuid>4c9e6f4f-b822-47d3-95eb-8565c49e3c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[3]/preceding::a[1]</value>
      <webElementGuid>be4a1a3d-5a79-48f1-9e3f-9d4ae4b8599e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[3]/preceding::a[2]</value>
      <webElementGuid>b1619e8c-0f0c-4aca-85dd-b0a3604827e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.facebook.com/petronas/')])[3]</value>
      <webElementGuid>924f9288-f908-48e6-b556-cf8cbdf85196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li/a</value>
      <webElementGuid>8acae082-dcf7-41c0-8f7f-5a76f59f8603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.facebook.com/petronas/' and (text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>5b203162-4141-4744-abd8-ed1a0a810c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
