<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instagram</name>
   <tag></tag>
   <elementGuidId>7b56a4ce-d402-462e-97f0-cf5fb54bda0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.JindexFooterIN.JsocialIN.JindexNaviRightBtmSocialIN.nav-link.JindexFooterINJsocialINJindexNaviRightBtmSocialIN.nav-link-https--wwwinstagramcom-petronas-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0053cbdb-ca5f-4fe5-8c9d-93528652587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.instagram.com/petronas/</value>
      <webElementGuid>5ae87403-db7c-4365-b164-50c067b97b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>130b3e85-c40d-45cd-b5f9-c9c35ff59765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JindexFooterIN JsocialIN JindexNaviRightBtmSocialIN nav-link JindexFooterINJsocialINJindexNaviRightBtmSocialIN nav-link-https--wwwinstagramcom-petronas-</value>
      <webElementGuid>55f2f143-434a-464f-b817-a5c8cc925d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instagram</value>
      <webElementGuid>4658b723-efca-47f7-8ad9-830810bb20dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexHomeDesktop&quot;]/div[@class=&quot;JindexFooter&quot;]/div[@class=&quot;JindexFooterInner&quot;]/div[@class=&quot;JindexFooterInnerBtm&quot;]/div[@class=&quot;JindexFooterInnerBtmRight&quot;]/ul[@class=&quot;clearfix nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;JindexFooterIN JsocialIN JindexNaviRightBtmSocialIN nav-link JindexFooterINJsocialINJindexNaviRightBtmSocialIN nav-link-https--wwwinstagramcom-petronas-&quot;]</value>
      <webElementGuid>0780ab2d-d63d-428e-9b69-9a185fa35ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[2]/a</value>
      <webElementGuid>e3e8b5cb-24e6-472d-b76f-d344ef9c5f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Instagram')])[3]</value>
      <webElementGuid>cb85d73c-240d-4fcb-bb4f-9653ccb27c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[3]/following::a[1]</value>
      <webElementGuid>e86f267a-6530-4bb2-87fe-9e15d716d580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(20076-K)'])[1]/following::a[2]</value>
      <webElementGuid>2881f045-0a66-4c54-9777-1102dfd12548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[3]/preceding::a[1]</value>
      <webElementGuid>23ec8014-d42c-4a00-af64-2f7b40212eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[3]/preceding::a[2]</value>
      <webElementGuid>a96fc4c7-6d74-4917-8a4e-9086fc07ca10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.instagram.com/petronas/')])[3]</value>
      <webElementGuid>13649c98-44c1-4d98-9d2c-18dd3d85003f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li[2]/a</value>
      <webElementGuid>c1a82083-e939-4ea8-8a59-96de2cabedea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.instagram.com/petronas/' and (text() = 'Instagram' or . = 'Instagram')]</value>
      <webElementGuid>1f8529de-492f-4444-a63d-a22182424aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
