<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LinkedIn</name>
   <tag></tag>
   <elementGuidId>1d71cced-9817-46d1-8fb3-a05e0044a017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.JindexFooterLI.JsocialLI.JindexNaviRightBtmSocialLI.nav-link.JindexFooterLIJsocialLIJindexNaviRightBtmSocialLI.nav-link-https--wwwlinkedincom-company-petronas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac83e24d-b429-4b66-89a8-18d4f01f7c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.linkedin.com/company/petronas</value>
      <webElementGuid>05274be0-d0a7-4d5f-83bc-cb2c43f2d3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>70845398-9ef9-411c-98b8-9d5c63386d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JindexFooterLI JsocialLI JindexNaviRightBtmSocialLI nav-link JindexFooterLIJsocialLIJindexNaviRightBtmSocialLI nav-link-https--wwwlinkedincom-company-petronas</value>
      <webElementGuid>c2c8a44a-b7e2-4f6e-b3a3-74f600c03a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LinkedIn</value>
      <webElementGuid>f058cb4d-bd4f-4847-b552-19fb5a235138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexHomeDesktop&quot;]/div[@class=&quot;JindexFooter&quot;]/div[@class=&quot;JindexFooterInner&quot;]/div[@class=&quot;JindexFooterInnerBtm&quot;]/div[@class=&quot;JindexFooterInnerBtmRight&quot;]/ul[@class=&quot;clearfix nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;JindexFooterLI JsocialLI JindexNaviRightBtmSocialLI nav-link JindexFooterLIJsocialLIJindexNaviRightBtmSocialLI nav-link-https--wwwlinkedincom-company-petronas&quot;]</value>
      <webElementGuid>35886c23-4400-4134-8c8c-6b91fc353341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[5]/a</value>
      <webElementGuid>7b357488-67e6-4537-a644-3fe152d116ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'LinkedIn')])[3]</value>
      <webElementGuid>2eff5667-4c2d-4caf-93f6-5cfcc0e508fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[3]/following::a[1]</value>
      <webElementGuid>30e9194d-78d9-4041-b598-c19906f5a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[3]/following::a[2]</value>
      <webElementGuid>86cea166-1f8c-41df-b1c7-dee01057e050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TikTok'])[3]/preceding::a[1]</value>
      <webElementGuid>f9589a8c-3d49-4878-82a5-9f7ac6b75753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passionate about Progress'])[2]/preceding::a[2]</value>
      <webElementGuid>f3eeb83c-afbc-44c3-a3b0-6584aa53b53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.linkedin.com/company/petronas')])[3]</value>
      <webElementGuid>4352ddeb-5158-490b-b995-133b55d140a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li[5]/a</value>
      <webElementGuid>01f71a40-931c-4e8d-96af-273419e9052e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.linkedin.com/company/petronas' and (text() = 'LinkedIn' or . = 'LinkedIn')]</value>
      <webElementGuid>11b6f1a8-98ff-4e42-8ea9-e8210774e72e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
