<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Our Approach to Sustainability</name>
   <tag></tag>
   <elementGuidId>2b5a1bf9-13f6-4ebf-93da-8c536f4f44f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[2]/div/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-link--sustainability-our-approach-to-sustainability</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>225fc222-79f2-4742-9011-43cc6da39c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sustainability/our-approach-to-sustainability</value>
      <webElementGuid>36bbaf92-b319-473f-be32-c7ea3b90ef7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link--sustainability-our-approach-to-sustainability</value>
      <webElementGuid>33e2fdcb-b649-400b-ba3c-ba80aa16d835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/1236</value>
      <webElementGuid>096a4115-cc20-4212-8770-05ecaee8bbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Approach to Sustainability</value>
      <webElementGuid>df4abc13-3180-4c60-9b53-00783ff3a018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexNaviContainer active show&quot;]/div[@class=&quot;JindexNaviContainerInner&quot;]/div[@class=&quot;JindexNaviRight&quot;]/div[@class=&quot;JindexNaviRightBtm&quot;]/ul[@class=&quot;clearfix JindexNaviRightBtmNavi&quot;]/li[@class=&quot;JhasSub&quot;]/div[@class=&quot;JhasSubInner&quot;]/div[@class=&quot;JhasSubInnerInner&quot;]/ul[1]/li[4]/a[@class=&quot;nav-link--sustainability-our-approach-to-sustainability&quot;]</value>
      <webElementGuid>ce9c746e-99c5-45a9-8f40-e22af3ee28eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>9bba5198-fe96-425c-b509-47678623208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Our Approach to Sustainability')]</value>
      <webElementGuid>318c4def-4b3b-4a3b-afd6-7243ce6b736c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Governance and Ethics'])[1]/following::a[1]</value>
      <webElementGuid>c629a85e-2be2-47d7-992e-96c5b5ed8e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sustainability Reporting'])[1]/following::a[2]</value>
      <webElementGuid>e4d8db1f-8f6b-4cb3-b6d2-17d29ec2f758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting to Net Zero'])[1]/preceding::a[1]</value>
      <webElementGuid>0873709e-ccf6-4c74-9693-21a1a5756c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Four Sustainability Lenses'])[1]/preceding::a[2]</value>
      <webElementGuid>11d9ef47-8b01-4d1a-84b3-95f025e3920f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our Approach to Sustainability']/parent::*</value>
      <webElementGuid>58823382-c15a-4d5b-bd26-79af74d393d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/sustainability/our-approach-to-sustainability')]</value>
      <webElementGuid>49bffd97-4a32-40b9-ad4e-d55fe2dc2422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>15601266-aa56-4448-96f4-017365c727bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sustainability/our-approach-to-sustainability' and (text() = 'Our Approach to Sustainability' or . = 'Our Approach to Sustainability')]</value>
      <webElementGuid>71c51334-332a-461d-93ed-26e521726244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
