<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TikTok</name>
   <tag></tag>
   <elementGuidId>827ecb6c-a208-4301-9917-6abcc72b338f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.JsocialTok.JindexNaviRightBtmSocialTok.JindexFooterTok.nav-link.JsocialTokJindexNaviRightBtmSocialTokJindexFooterTok.nav-link-https--wwwtiktokcom-petronas-official</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb92a331-74e7-435b-a701-5ba81fc86118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.tiktok.com/@petronas_official</value>
      <webElementGuid>c28c1aea-7953-4961-90f3-6ec5096e066d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ff943630-b5fd-488b-a249-ba7570f2341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JsocialTok JindexNaviRightBtmSocialTok JindexFooterTok nav-link JsocialTokJindexNaviRightBtmSocialTokJindexFooterTok nav-link-https--wwwtiktokcom-petronas-official</value>
      <webElementGuid>1874f9c0-051e-497b-a314-e083a30b0b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TikTok</value>
      <webElementGuid>884354db-3764-4aea-9a29-b147b922dffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexHomeDesktop&quot;]/div[@class=&quot;JindexFooter&quot;]/div[@class=&quot;JindexFooterInner&quot;]/div[@class=&quot;JindexFooterInnerBtm&quot;]/div[@class=&quot;JindexFooterInnerBtmRight&quot;]/ul[@class=&quot;clearfix nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;JsocialTok JindexNaviRightBtmSocialTok JindexFooterTok nav-link JsocialTokJindexNaviRightBtmSocialTokJindexFooterTok nav-link-https--wwwtiktokcom-petronas-official&quot;]</value>
      <webElementGuid>37e653d5-4e56-476c-8897-ea8ad7a84a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[6]/a</value>
      <webElementGuid>780da269-c6e3-4b2e-a157-6c5da22af508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'TikTok')])[3]</value>
      <webElementGuid>ceed3533-b80f-435d-befe-75a78ea396ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[3]/following::a[1]</value>
      <webElementGuid>7b4499c8-6d9d-4f94-b5d5-5eba05dd980d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[3]/following::a[2]</value>
      <webElementGuid>2eb00cfb-023f-4d64-bbf4-26fc335ad3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passionate about Progress'])[2]/preceding::a[1]</value>
      <webElementGuid>410d2630-2e3a-4516-b87f-896540318aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advocating Transparency'])[2]/preceding::a[3]</value>
      <webElementGuid>9b8cdb1d-440f-4552-b51b-13c24b810146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.tiktok.com/@petronas_official')])[3]</value>
      <webElementGuid>27dd835e-cae1-44d7-b71c-446a44601e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li[6]/a</value>
      <webElementGuid>98d5855f-1834-48d9-a485-cb87d7d571d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.tiktok.com/@petronas_official' and (text() = 'TikTok' or . = 'TikTok')]</value>
      <webElementGuid>70c4f3e7-19aa-49cb-a3b4-4286f1d73e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
