<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Twitter</name>
   <tag></tag>
   <elementGuidId>982038c2-5c2e-430d-b294-c26f0e37a008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.JindexFooterTT.JsocialTT.JindexNaviRightBtmSocialTT.nav-link.JindexFooterTTJsocialTTJindexNaviRightBtmSocialTT.nav-link-https--twittercom-petronas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ba56f91-4ce1-40cf-8180-bcf106133664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/Petronas</value>
      <webElementGuid>2d20203f-65ec-436d-b4f6-1a5bd3ff2c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a5eb62b1-f321-4d16-a842-bf14c10a6dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JindexFooterTT JsocialTT JindexNaviRightBtmSocialTT nav-link JindexFooterTTJsocialTTJindexNaviRightBtmSocialTT nav-link-https--twittercom-petronas</value>
      <webElementGuid>e8c1c02a-88c0-4a34-841f-e02014601b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>755c961c-2388-4bb9-92ab-d08138047954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexHomeDesktop&quot;]/div[@class=&quot;JindexFooter&quot;]/div[@class=&quot;JindexFooterInner&quot;]/div[@class=&quot;JindexFooterInnerBtm&quot;]/div[@class=&quot;JindexFooterInnerBtmRight&quot;]/ul[@class=&quot;clearfix nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;JindexFooterTT JsocialTT JindexNaviRightBtmSocialTT nav-link JindexFooterTTJsocialTTJindexNaviRightBtmSocialTT nav-link-https--twittercom-petronas&quot;]</value>
      <webElementGuid>3591a4f6-abc4-4508-b2e9-b8b222cf8673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[11]/div[3]/div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>fefc3f1f-ac7b-4823-9d6a-94f679cf574e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Twitter')])[3]</value>
      <webElementGuid>9e0a081c-8be3-4465-a6f3-b38b122f2703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[3]/following::a[1]</value>
      <webElementGuid>1e80f695-7baf-43a6-8e82-195f44c9488f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[3]/following::a[2]</value>
      <webElementGuid>a5512e0b-c3df-4625-a1d8-dd5b2dd8851c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[3]/preceding::a[1]</value>
      <webElementGuid>9451d51d-02ab-414b-ae5d-c6d26f111b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[3]/preceding::a[2]</value>
      <webElementGuid>1444dd37-930b-4991-9537-37cfbb1f56a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://twitter.com/Petronas')])[3]</value>
      <webElementGuid>5f86db8d-3643-4e7f-a50a-4ad7a43156bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>c326fa7e-0e92-466a-af21-c6ba8a59b9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://twitter.com/Petronas' and (text() = 'Twitter' or . = 'Twitter')]</value>
      <webElementGuid>6d072523-02f6-4646-8d6a-ef2f6a18735a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
