<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Getting to Net Zero</name>
   <tag></tag>
   <elementGuidId>1c445c1b-b207-43ab-a219-42befe975b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link--sustainability-getting-to-net-zero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[2]/div/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77fe587b-cb51-44d6-84a5-2632efcc83b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sustainability/getting-to-net-zero</value>
      <webElementGuid>0ae7fbfd-31b9-48e9-8c21-63c5a6cd4b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link--sustainability-getting-to-net-zero</value>
      <webElementGuid>1de118af-40db-485e-a9ab-e441e22a1ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/673</value>
      <webElementGuid>7beb0c16-2204-4af1-9791-75de9f342d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Getting to Net Zero</value>
      <webElementGuid>553a375e-52b2-41d5-a2c3-68a138be9fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexNaviContainer active show&quot;]/div[@class=&quot;JindexNaviContainerInner&quot;]/div[@class=&quot;JindexNaviRight&quot;]/div[@class=&quot;JindexNaviRightBtm&quot;]/ul[@class=&quot;clearfix JindexNaviRightBtmNavi&quot;]/li[@class=&quot;active JhasSub&quot;]/div[@class=&quot;JhasSubInner&quot;]/div[@class=&quot;JhasSubInnerInner&quot;]/ul[1]/li[5]/a[@class=&quot;nav-link--sustainability-getting-to-net-zero&quot;]</value>
      <webElementGuid>5f5a19d5-7fdf-44cd-ac54-21c8a62e7e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>67f4b86f-8933-41c6-ac3c-830c602b6021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Getting to Net Zero')]</value>
      <webElementGuid>cccd31d9-542c-436f-a084-069f41690310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Approach to Sustainability'])[1]/following::a[1]</value>
      <webElementGuid>e7b50ab9-44cf-4d72-b356-a78dd6009c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Governance and Ethics'])[1]/following::a[2]</value>
      <webElementGuid>f1a078f8-f1c0-482d-ac4d-651d18bb3de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Four Sustainability Lenses'])[1]/preceding::a[1]</value>
      <webElementGuid>6ba6d24e-1de5-4907-a98f-d5647911bd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progressing Energy'])[1]/preceding::a[2]</value>
      <webElementGuid>b4a03fb5-8dbe-4ba3-9afb-7cc4ce77b8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Getting to Net Zero']/parent::*</value>
      <webElementGuid>944996ad-a67a-4655-9450-886e01ae038e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/sustainability/getting-to-net-zero')]</value>
      <webElementGuid>c922c085-0c5a-4270-8fd5-5e7a87658a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>5635e0bf-5657-4f32-bb1e-997445e3bca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sustainability/getting-to-net-zero' and (text() = 'Getting to Net Zero' or . = 'Getting to Net Zero')]</value>
      <webElementGuid>66abbdf2-1dfd-4dea-8c8c-e9c2944061db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
