<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview</name>
   <tag></tag>
   <elementGuidId>0539d818-26ad-483c-be88-63afe43ef005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link--investor-relations</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[4]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c803e7e-b390-49e2-85fb-f73e79eb2398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/investor-relations</value>
      <webElementGuid>46d5de1c-14fe-430f-870b-ab207cb78074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link--investor-relations</value>
      <webElementGuid>c7f5db42-bf4b-4145-b474-f118b54aa3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/655</value>
      <webElementGuid>ac7717fd-6d1a-4fa0-96d0-ee7971aef3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>317fc104-1275-4715-a198-ef85bd52ec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;JindexNaviContainer active show&quot;]/div[@class=&quot;JindexNaviContainerInner&quot;]/div[@class=&quot;JindexNaviRight&quot;]/div[@class=&quot;JindexNaviRightBtm&quot;]/ul[@class=&quot;clearfix JindexNaviRightBtmNavi&quot;]/li[@class=&quot;JhasSub&quot;]/div[@class=&quot;JhasSubInner&quot;]/div[@class=&quot;JhasSubInnerInner&quot;]/ul[1]/li[1]/a[@class=&quot;nav-link--investor-relations&quot;]</value>
      <webElementGuid>4e473f1b-0790-4f7c-a816-6d6587733a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div[2]/div[2]/ul/li[4]/div/div/ul/li/a</value>
      <webElementGuid>06ec20b9-1337-49fd-89c8-942e266ad33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Overview')])[7]</value>
      <webElementGuid>cc69cd27-fb98-4275-a8fa-dc0e1b70aa38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Relations'])[1]/following::a[1]</value>
      <webElementGuid>2955b4d6-82da-47a7-9379-d0c5cec94ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Solutions'])[1]/following::a[2]</value>
      <webElementGuid>ad2d4e6b-168f-44a4-a453-6f3d672fc65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Integrated Report 2022'])[1]/preceding::a[1]</value>
      <webElementGuid>fd857a6d-23ea-4ea6-8aad-e5fa1832dbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Activity Outlook'])[1]/preceding::a[2]</value>
      <webElementGuid>5eb48ec4-faa7-44ac-a7ab-392b79545301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/investor-relations')]</value>
      <webElementGuid>0ebcc22a-a1c5-49e8-af71-d58bf1b60d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/div/div/ul/li/a</value>
      <webElementGuid>55b35be8-b024-4acc-81d5-e774c48e1f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/investor-relations' and (text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>a988d1bf-bfef-4155-b540-9509c7755328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
