<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tan Sri Tengku Muhammad Taufik_JmasterR_c7edd3</name>
   <tag></tag>
   <elementGuidId>54a6a15d-d9c6-4940-bf6e-457ba9ca5997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.JmasterRow7ContentBanner.aos-init.aos-animate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[6]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ae8911b-1482-4825-90a2-20a7f8890aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JmasterRow7ContentBanner aos-init aos-animate</value>
      <webElementGuid>5a4077cb-1008-49ab-bd36-406d467fb2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aos</name>
      <type>Main</type>
      <value>zoom-out</value>
      <webElementGuid>0b17d037-7072-4cf2-adc8-a40670b3c9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aos-anchor-placement</name>
      <type>Main</type>
      <value>top-bottom</value>
      <webElementGuid>af74ec33-d1fa-42b9-bd31-6e97954e58a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;pelement-id--819f338 JsustainabilityRow3 paragraph paragraph--type--section-image-top-content-bottom paragraph--view-mode--default JmasterRow7Container&quot;]/div[@class=&quot;JmasterRow7ContainerInner&quot;]/div[@class=&quot;JmasterRow7Content&quot;]/div[@class=&quot;JmasterRow7ContentBanner aos-init aos-animate&quot;]</value>
      <webElementGuid>5b8316bf-6be7-4a3e-b4ee-05253cf618ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[6]/div/div[2]/div</value>
      <webElementGuid>884ee51e-93c4-4492-8301-74b54d5aee0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>b67a6a9a-b3f4-4693-b287-f899806709d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
