<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Subscribe Now</name>
   <tag></tag>
   <elementGuidId>37d3948e-107a-48c3-a2f6-ceff4814b5d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JgeneralSlider-slide03 > div.JgeneralFooterSliderContent > a > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='JgeneralSlider-slide03']/div[3]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c891b434-2854-4ab3-a0f0-263fcfe2f7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe Now</value>
      <webElementGuid>b24218e0-c3ee-4529-b817-0b2e84912a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JgeneralSlider-slide03&quot;)/div[@class=&quot;JgeneralFooterSliderContent&quot;]/a[1]/p[1]</value>
      <webElementGuid>3adb4b31-345a-43e6-9c1b-e62333281e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='JgeneralSlider-slide03']/div[3]/a/p</value>
      <webElementGuid>7cb34251-678f-462a-a0c2-fb64b27f3ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect With Us'])[2]/following::p[2]</value>
      <webElementGuid>2004824a-7eb0-489c-a417-64cc5a506fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Opportunities'])[4]/following::p[4]</value>
      <webElementGuid>224eb39e-2c27-4e62-b3aa-ad3f059fbcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Governance and Ethics'])[3]/preceding::p[1]</value>
      <webElementGuid>67b522c2-8afb-429d-a3c0-782cd2151871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Opportunities'])[5]/preceding::p[3]</value>
      <webElementGuid>4030c418-4cf8-4f45-8694-41ae8cf2e0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[3]/a/p</value>
      <webElementGuid>5e664427-6f66-41ab-9500-a89e90193c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Subscribe Now' or . = 'Subscribe Now')]</value>
      <webElementGuid>be28f100-cf62-4f8d-a039-f8a3f6628269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
