<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Governance and Ethics_splide__arrow _d88321</name>
   <tag></tag>
   <elementGuidId>b6f93851-7fb5-4596-ac28-9b3900cb76ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.splide__arrow.splide__arrow--prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfbb1010-c745-4b72-bcc6-5d445963f46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>splide__arrow splide__arrow--prev</value>
      <webElementGuid>1d380fd5-8cfe-4ea3-8e2b-2e69294b08ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff105a17-259a-4cea-9acc-de251276925a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Go to last slide</value>
      <webElementGuid>8fc89c3e-b9bd-4868-a3ae-f917097422a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>JgeneralSlider-track</value>
      <webElementGuid>99b34ef2-cb30-462d-9fd0-3e75a8d246ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JgeneralSlider&quot;)/div[@class=&quot;JgeneralFooterSliderNavi&quot;]/div[@class=&quot;JgeneralFooterSliderNaviInner&quot;]/div[@class=&quot;splide__arrows splide__arrows--ltr&quot;]/button[@class=&quot;splide__arrow splide__arrow--prev&quot;]</value>
      <webElementGuid>4ac9385a-f06f-48bd-8452-bcf1d0ec5378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>3014f9d5-de23-4bf7-a110-82087fb5c077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='JgeneralSlider']/div[2]/div/div/button</value>
      <webElementGuid>2a3c6393-b992-4dc4-93a7-e5947f065a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Governance and Ethics'])[4]/following::button[1]</value>
      <webElementGuid>5716dca3-f624-493f-a9f1-9915b707dedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Licensing &amp; Procurement In Malaysia'])[4]/following::button[1]</value>
      <webElementGuid>6e92bbe9-d62a-4cbd-9518-a4e969d4b124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[2]</value>
      <webElementGuid>fdb3f746-d586-479c-8930-9f83b909acc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect With Us'])[2]/preceding::button[2]</value>
      <webElementGuid>c5aea075-5e1b-4945-b28b-f60dfe922ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>601780de-6a88-4ae0-9db6-d847420e5880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>9ba5704e-ba5f-4a50-8b02-75a04b3fd02a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
