<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PETRONAS Chemicals Group Berhad_spli_749532</name>
   <tag></tag>
   <elementGuidId>ebbdb69b-b34f-41f6-8a17-a7a03dd59fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.splide__arrow.splide__arrow--next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2f0780d-a8f1-4e9b-82c9-3d843fd600cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>splide__arrow splide__arrow--next</value>
      <webElementGuid>1e30ff8f-db01-4be5-8cd8-ae7b25bd3e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b871cc24-e5a4-497a-9635-c3c4376c4c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next slide</value>
      <webElementGuid>a3f7890f-1bc7-4972-b7d1-46c8d1873a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sliderG2-track</value>
      <webElementGuid>07c73680-fc91-469d-8a2e-6d15960ecf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sliderG2&quot;)/div[@class=&quot;JindexRow3SplideNavi aos-init aos-animate&quot;]/div[@class=&quot;JindexRow3SplideNaviInner&quot;]/div[@class=&quot;splide__arrows splide__arrows--ltr&quot;]/button[@class=&quot;splide__arrow splide__arrow--next&quot;]</value>
      <webElementGuid>10b31c82-1672-449a-95e8-c3e06f87e00f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>497ebd54-5573-4318-8f96-ffbda210e0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sliderG2']/div[2]/div/div/button[2]</value>
      <webElementGuid>9c56a51e-9a6c-4b57-93af-dd105c303712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Chemicals Group Berhad'])[3]/following::button[2]</value>
      <webElementGuid>0f27a917-97e7-4871-957a-940e3e6571f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Highlights'])[7]/following::button[2]</value>
      <webElementGuid>5dec3e88-1c60-4705-9db9-9d53ab677f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Results'])[2]/preceding::button[4]</value>
      <webElementGuid>54854556-44f3-43aa-82b1-db18fe7fedf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Operational Reports'])[2]/preceding::button[4]</value>
      <webElementGuid>833e0436-83a5-4e60-ae01-d034c86c4ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e190ae67-653b-4fa3-97d8-230f7f4bf3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>0df7ebfa-0720-4bfa-97c2-06991d76cd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
